words = [
    "jujutsu",
    "pkgs",
    "thekorn",
    "nixos",
    "macbook",
    "BFG",
    "Homebrew",
    "lefthook",
    "rpi",
    "nvim",
    "nixpkgs",
    "Afee",
    "neovim",
    "lazyvim",
    "OSX",
    "qmk",
    "gmmk",
]


ignore_paths = ["keyboards/**", "home/**", "flake.*", "rpi/**", "hosts/**"]
